/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.mancheng.cn.techproof.api;

import com.mancheng.cn.techproof.model.BaiduHomePageData;
import com.mancheng.cn.techproof.model.BaiduHomePageResponseData;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@Api(value = "baiduHome", description = "the baiduHome API")
public interface BaiduHomeApi {

    @ApiOperation(value = "", nickname = "baiduHomePageInfo", notes = "", response = BaiduHomePageResponseData.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaiduHomePageResponseData.class),
        @ApiResponse(code = 404, message = "Resource Not Found") })
    @RequestMapping(value = "/baiduHome/v1",
        produces = { "application/json" }, 
        consumes = { "*/*" },
        method = RequestMethod.POST)
    ResponseEntity<BaiduHomePageResponseData> baiduHomePageInfo(@ApiParam(value = "baidu homepage info parameters"  )  @Valid @RequestBody BaiduHomePageData body);

}
